# Site Info
title:              "Today I Learned"
description:        "Collection of tips and tricks I've picked up allong the way."
google_verify:      epFgX0s_0RM3CdjwFcsewfXzPov2g8s9ZBOLyaIUH-o # Put your Google Verification here
google_analytics:   UA-XXXXXXX-X # Put your Google Analytics code

# Author Info
author_name:        "Dario Fuzinato" # Your name here
author_email:       fussinatto@gmail.com # Your email here
author_gravatar:    2b38b1b0e7e08b69379bd61582adf0c8 # Your Gravatar md5 hash here for logo
twitter_username:   fussinatto # Your Twitter username here
github_username:    fuzinato # Your GitHub username here

# Site Settings
url:                https://til.dario.sh # main url
baseurl:            / # for gh-pages
permalink:          /til/:title # Post permalink
timezone:           Europe/Berlin # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
mathjax:            false  # enables support for mathjax - set to false to disable

# Site Build
highlighter:        rouge
markdown:           kramdown
kramdown:
    input:          GFM
sass:
    style:          :compressed

# Other Params
include:            [ "robots.txt" ]
exclude:            [ "LICENSE", "README.md", "CNAME", "vendor", "Gemfile" ]
plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-paginate

paginate: 15


defaults:
  -
    scope:
      path:         ""
    values:
      layout:       "null"
  -
    scope:
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      type:         "posts"
    values:
      layout:       "post"
